version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: True
  redis:
    image: "redis:alpine"
  promethus:
    image: "prom/prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  docker_exporter:
    image: "prometheusnet/docker_exporter"
    ports: ["9417:9417"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
